
import NewsList from '@/Components/NewsList'
import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-full'>
        <div className='mt-10 mx-5 text-center'>
          <h2 className='text-2xl'>
            Welcome to CNC, the place to get all the latest news from the US: Business, Sports, Tech, Entertainment, and many more.
          </h2>
        </div>
        <NewsList />
      </div>
    </>
  )
}
